name: LimitLoot
version: ${project.version}
main: net.snofox.minecraft.limitloot.LimitLoot
api-version: 1.13
authors: [SnoFox]
description: Prevent loot and other progression outside of a world boarder
depend: ["SnoLib"]
softdepend: ["CraftRegions"]
